site_name: "Interactive Clustering"
site_description: "Python package used to apply NLP interactive clustering methods."
site_url: "https://cognitivefactory.github.io/interactive-clustering"
repo_url: "https://github.com/cognitivefactory/interactive-clustering"
repo_name: "cognitivefactory/interactive-clustering"
site_dir: "site"
watch: [README.md, CONTRIBUTING.md, CHANGELOG.md, src/cognitivefactory/interactive_clustering]

nav:
- Home:
  - Overview: index.md
  - Usage: usage.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
# defer to gen-files + literate-nav
- Code Reference: reference/
####  - Constraints Managing:
####    - constraints.abstract: reference/constraints/abstract.md
####    - constraints.factory: reference/constraints/factory.md
####    - constraints.binary: reference/constraints/binary.md
####  - Constraints Sampling:
####    - sampling.abstract: reference/sampling/abstract.md
####    - sampling.factory: reference/sampling/factory.md
####    - sampling.clusters_based: reference/sampling/clusters_based.md
####  - Constrained Clustering:
####    - clustering.abstract: reference/clustering/abstract.md
####    - clustering.factory: reference/clustering/factory.md
####    - clustering.kmeans: reference/clustering/kmeans.md
####    - clustering.hierarchical: reference/clustering/hierarchical.md
####    - clustering.spectral: reference/clustering/spectral.md
####    - clustering.affinity_propagation: reference/clustering/affinity_propagation.md
####    - clustering.dbscan: reference/clustering/dbscan.md
####    - clustering.mpckmeans: reference/clustering/mpckmeans.md
####  - Utility methods:
####    - utils.preprocessing: reference/utils/preprocessing.md
####    - utils.vectorization: reference/utils/vectorization.md
####    - utils.frequency: reference/utils/frequency.md
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
- admonition
- callouts
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: true

plugins:
- search
- markdown-exec
- gen-files:
    scripts:
    - docs/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.md
- coverage
- section-index
- mkdocstrings:
    watch:
    - src/cognitivefactory/

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/erwanschild
